import { SEO } from "@/components/SEO";
import { Navigation } from "@/components/Navigation";
import { Footer } from "@/components/Footer";

export default function Privacy() {
  return (
    <>
      <SEO
        title="Privacy Policy | Voiceable"
        description="Voiceable Privacy Policy - Learn how we collect, safeguard and disclose information that results from your use of our Service."
        keywords="privacy policy, data protection, GDPR, CCPA, privacy rights"
        url="https://www.voiceable.dev/privacy"
      />
      <div className="min-h-screen bg-background">
        <Navigation />

        <div className="pt-32 pb-24">
          <div className="max-w-7xl mx-auto px-6">
            <div className="prose prose-slate dark:prose-invert max-w-none">
            <h1 className="text-4xl md:text-5xl font-bold mb-4">Voiceable - Privacy Policy</h1>
            <p className="text-muted-foreground mb-8">Last Updated: January 15, 2025</p>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Introduction</h2>
              <p className="text-foreground mb-4">
                Welcome to Voiceable, a product of Voiceable Inc.
              </p>
              <p className="text-foreground mb-4">
                Voiceable Inc. ("us", "we", or "our") operates https://voiceable.ai (hereinafter referred to as "Service").
              </p>
              <p className="text-foreground mb-4">
                Our Privacy Policy governs your visit to https://voiceable.ai, and explains how we collect, safeguard and disclose information that results from your use of our Service.
              </p>
              <p className="text-foreground mb-4">
                We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
              </p>
              <p className="text-foreground">
                Our Terms and Conditions ("Terms") govern all use of our Service and together with the Privacy Policy constitutes your agreement with us ("agreement").
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Definitions</h2>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li><strong>SERVICE</strong> means the https://voiceable.ai website operated by Voiceable Inc.</li>
                <li><strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</li>
                <li><strong>USAGE DATA</strong> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</li>
                <li><strong>COOKIES</strong> are small files stored on your device (computer or mobile device).</li>
                <li><strong>DATA CONTROLLER</strong> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</li>
                <li><strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</li>
                <li><strong>DATA SUBJECT</strong> is any living individual who is the subject of Personal Data.</li>
                <li><strong>THE USER</strong> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Information Collection and Use</h2>
              <p className="text-foreground mb-4">
                We collect several different types of information for various purposes to provide and improve our Service to you.
              </p>

              <h3 className="text-xl font-semibold mb-3 mt-6">Types of Data Collected</h3>

              <h4 className="text-lg font-semibold mb-2 mt-4">Personal Data</h4>
              <p className="text-foreground mb-4">
                While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-foreground mb-4">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Cookies and Usage Data</li>
              </ul>
              <p className="text-foreground mb-4">
                We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.
              </p>

              <h4 className="text-lg font-semibold mb-2 mt-4">Usage Data</h4>
              <p className="text-foreground mb-4">
                We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a mobile device ("Usage Data").
              </p>
              <p className="text-foreground mb-4">
                This Usage Data may include information such as your computer's Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              </p>
              <p className="text-foreground mb-4">
                When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
              </p>

              <h4 className="text-lg font-semibold mb-2 mt-4">Location Data</h4>
              <p className="text-foreground mb-4">
                We may use and store information about your location if you give us permission to do so ("Location Data"). We use this data to provide features of our Service, to improve and customize our Service.
              </p>
              <p className="text-foreground mb-4">
                You can enable or disable location services when you use our Service at any time by way of your device settings.
              </p>

              <h4 className="text-lg font-semibold mb-2 mt-4">Tracking & Cookies Data</h4>
              <p className="text-foreground mb-4">
                We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
              </p>
              <p className="text-foreground mb-4">
                Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags, and scripts to collect and track information and to improve and analyze our Service.
              </p>
              <p className="text-foreground mb-4">
                You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
              </p>
              <p className="text-foreground mb-2">Examples of Cookies we use:</p>
              <ul className="list-disc pl-6 space-y-2 text-foreground mb-4">
                <li><strong>Session Cookies:</strong> We use Session Cookies to operate our Service.</li>
                <li><strong>Preference Cookies:</strong> We use Preference Cookies to remember your preferences and various settings.</li>
                <li><strong>Security Cookies:</strong> We use Security Cookies for security purposes.</li>
                <li><strong>Advertising Cookies:</strong> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</li>
              </ul>

              <h4 className="text-lg font-semibold mb-2 mt-4">Platform Data</h4>
              <p className="text-foreground mb-4">
                Voiceable is a voice AI platform that facilitates conversations with voicebots. To enable our service, we process and store certain information related to the calls, assistants, credentials and phone numbers as outlined below. We act as a data processor on behalf of our customers.
              </p>

              <h5 className="text-md font-semibold mb-2 mt-3">1. Assistants</h5>
              <p className="text-foreground mb-4">
                When customers create AI assistants using our platform, we store the configuration settings, prompts, and any training data or templates used to build the assistant's conversational abilities. This may include sample phrases, knowledge base content, dialog flows, and AI model parameters. Assistant data is kept for as long as the customer maintains their assistant on our platform.
              </p>

              <h5 className="text-md font-semibold mb-2 mt-3">2. Calls</h5>
              <p className="text-foreground mb-4">
                To provide the voice AI service, we process call audio in real-time to convert speech to text, apply natural language understanding and generate responses. Call data we collect includes:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-foreground mb-4">
                <li><strong>Call parties:</strong> Phone numbers or IPs of the parties on the call</li>
                <li><strong>Call metadata:</strong> Start and end times, call duration, call status (answered, busy, failed etc.).</li>
                <li><strong>Call media:</strong> Recordings of the call audio, if enabled by the customer</li>
                <li><strong>Call transcripts:</strong> Speech-to-text transcriptions of the call audio</li>
                <li><strong>Call logs:</strong> Details on the conversation flow, AI responses and outcomes</li>
              </ul>
              <p className="text-foreground mb-4">
                Call recordings, transcripts and logs may be retained to help train and improve the AI models, in accordance with applicable laws. Retention periods depend on the customer's configuration and data is deleted on request.
              </p>

              <h5 className="text-md font-semibold mb-2 mt-3">3. Credentials</h5>
              <p className="text-foreground mb-4">
                To connect with third-party services and providers that enable our voice AI functionality, we securely store necessary credentials, such as API keys, access tokens, and webhook URLs. These credentials are encrypted and accessible only to the Voiceable systems that require them to operate the service on the customer's behalf. Credentials are deleted upon customer request or when no longer needed.
              </p>

              <h5 className="text-md font-semibold mb-2 mt-3">4. Phone Numbers</h5>
              <p className="text-foreground mb-4">
                To provide inbound and outbound calling capabilities, we provision and store phone numbers that are assigned to our customers. This includes phone number metadata like the number itself, type (local, toll-free, short code), provider, region, and assignment (which customer or assistant is assigned the number).
              </p>

              <h4 className="text-lg font-semibold mb-2 mt-4">Other Data</h4>
              <p className="text-foreground mb-4">
                While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, non-disclosure agreements, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location, and other data.
              </p>
              <p className="text-foreground mb-4">
                We may also store customer contact numbers used for two-factor authentication, billing communications, or support, in accordance with applicable regulations like the GDPR.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Use of Data</h2>
              <p className="text-foreground mb-4">Voiceable Inc. uses the collected data for various purposes:</p>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li>to provide and maintain our Service;</li>
                <li>to notify you about changes to our Service;</li>
                <li>to allow you to participate in interactive features of our Service when you choose to do so;</li>
                <li>to provide customer support;</li>
                <li>to gather analysis or valuable information so that we can improve our Service;</li>
                <li>to monitor the usage of our Service;</li>
                <li>to detect, prevent, and address technical issues;</li>
                <li>to fulfill any other purpose for which you provide it;</li>
                <li>to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</li>
                <li>to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</li>
                <li>to provide you with news, special offers, and general information about other goods, services, and events which we offer that are similar to those that you have already purchased or inquired about unless you have opted not to receive such information;</li>
                <li>in any other way we may describe when you provide the information;</li>
                <li>for any other purpose with your consent.</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Google Workspace API Usage</h2>
              <p className="text-foreground">
                Our application does not use any data obtained through Google Workspace APIs to develop, improve, or train generalized AI and/or ML models. All data is used solely to provide and enhance the specific services for which it was collected.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Retention of Data</h2>
              <p className="text-foreground mb-4">
                We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
              </p>
              <p className="text-foreground">
                We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Transfer of Data</h2>
              <p className="text-foreground mb-4">
                Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
              </p>
              <p className="text-foreground mb-4">
                If you are located outside the United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to the United States and process it there.
              </p>
              <p className="text-foreground mb-4">
                Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
              </p>
              <p className="text-foreground">
                Voiceable Inc. will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Disclosure of Data</h2>
              <p className="text-foreground mb-4">We may disclose personal information that we collect, or you provide:</p>

              <h3 className="text-xl font-semibold mb-2 mt-4">Disclosure for Law Enforcement</h3>
              <p className="text-foreground mb-4">
                Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.
              </p>

              <h3 className="text-xl font-semibold mb-2 mt-4">Business Transaction</h3>
              <p className="text-foreground mb-4">
                If we or our subsidiaries are involved in a merger, acquisition, or asset sale, your Personal Data may be transferred.
              </p>

              <h3 className="text-xl font-semibold mb-2 mt-4">Other cases. We may disclose your information also:</h3>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li>to our subsidiaries and affiliates;</li>
                <li>to fulfill the purpose for which you provide it;</li>
                <li>for any other purpose disclosed by us when you provide the information;</li>
                <li>with your consent in any other cases;</li>
                <li>if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Security of Data</h2>
              <p className="text-foreground">
                The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h2>
              <p className="text-foreground mb-4">
                If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR. – See more at <a href="https://eur-lex.europa.eu/eli/reg/2016/679/oj" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">https://eur-lex.europa.eu/eli/reg/2016/679/oj</a>
              </p>
              <p className="text-foreground mb-4">
                We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
              </p>
              <p className="text-foreground mb-4">
                If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at support@voiceable.ai.
              </p>
              <p className="text-foreground mb-4">In certain circumstances, you have the following data protection rights:</p>
              <ul className="list-disc pl-6 space-y-2 text-foreground mb-4">
                <li>the right to access, update or to delete the information we have on you;</li>
                <li>the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;</li>
                <li>the right to object. You have the right to object to our processing of your Personal Data;</li>
                <li>the right of restriction. You have the right to request that we restrict the processing of your personal information;</li>
                <li>the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;</li>
                <li>the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;</li>
              </ul>
              <p className="text-foreground mb-4">
                Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.
              </p>
              <p className="text-foreground">
                You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)</h2>
              <p className="text-foreground mb-4">According to CalOPPA, we agree to the following:</p>
              <ul className="list-disc pl-6 space-y-2 text-foreground mb-4">
                <li>users can visit our site anonymously;</li>
                <li>our Privacy Policy link includes the word "Privacy", and can easily be found on the page specified above on the home page of our website;</li>
                <li>users will be notified of any privacy policy changes on our Privacy Policy Page;</li>
                <li>users are able to change their personal information by emailing us at support@voiceable.ai.</li>
              </ul>
              <h3 className="text-xl font-semibold mb-2 mt-4">Our Policy on "Do Not Track" Signals:</h3>
              <p className="text-foreground mb-4">
                We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.
              </p>
              <p className="text-foreground">
                You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Your Data Protection Rights under the California Consumer Privacy Act (CCPA)</h2>
              <p className="text-foreground mb-4">
                If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:
              </p>
              <p className="text-foreground mb-4">
                <strong>What personal information we have about you.</strong> If you make this request, we will return to you:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-foreground mb-4">
                <li>The categories of personal information we have collected about you.</li>
                <li>The categories of sources from which we collect your personal information.</li>
                <li>The business or commercial purpose for collecting or selling your personal information.</li>
                <li>The categories of third parties with whom we share personal information.</li>
                <li>The specific pieces of personal information we have collected about you.</li>
                <li>A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.</li>
                <li>A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.</li>
              </ul>
              <p className="text-foreground mb-4">
                Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.
              </p>
              <p className="text-foreground mb-4">
                <strong>To delete your personal information.</strong> If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.
              </p>
              <p className="text-foreground mb-4">
                <strong>To stop selling your personal information.</strong> We do not sell your personal information for monetary consideration. However, under some circumstances, a transfer of personal information to a third party, or within our family of companies, without monetary consideration may be considered a "sale" under California law.
              </p>
              <p className="text-foreground mb-4">
                If you submit a request to stop selling your personal information, we will stop making such transfers. If you are a California resident, to opt-out of the sale of your personal information, email support@voiceable.ai with the subject line "Do Not Sell My Personal Information" to submit your request.
              </p>
              <p className="text-foreground mb-4">
                Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services which require the usage of your personal information to function. But in no circumstances, we will discriminate against you for exercising your rights.
              </p>
              <p className="text-foreground mb-4">
                To exercise your California data protection rights described above, please send your request(s) to support@voiceable.ai.
              </p>
              <p className="text-foreground">
                Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To find out more, visit the official California Legislative Information website. The CCPA took effect on 01/01/2020.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Service Providers</h2>
              <p className="text-foreground mb-4">
                We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.
              </p>
              <p className="text-foreground mb-4">
                These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
              </p>
              <p className="text-foreground mb-4">
                You can request an up-to-date list of third-party Service Providers by emailing us at support@voiceable.ai. We provide a non-comphrensive list of our Service Providers below.
              </p>

              <h3 className="text-xl font-semibold mb-2 mt-4">Analytics</h3>
              <p className="text-foreground mb-4">We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
              <ul className="list-disc pl-6 space-y-2 text-foreground mb-4">
                <li><strong>Google Analytics:</strong> Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="https://policies.google.com/privacy?hl=en" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy?hl=en</a></li>
                <li><strong>Cloudflare Analytics:</strong> Cloudflare analytics is a web analytics service operated by Cloudflare Inc. Read the Privacy Policy here: <a href="https://www.cloudflare.com/privacypolicy/" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">https://www.cloudflare.com/privacypolicy/</a></li>
                <li><strong>Segment.io:</strong> Segment.io is a web traffic analysis tool. Read the Privacy Policy for Segment.io here: <a href="https://segment.com/legal/privacy/" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">https://segment.com/legal/privacy/</a></li>
                <li><strong>Mixpanel:</strong> Mixpanel is provided by Mixpanel Inc. You can prevent Mixpanel from using your information for analytics purposes by opting-out. To opt-out of Mixpanel service, please visit this page: <a href="https://mixpanel.com/optout/" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">https://mixpanel.com/optout/</a></li>
                <li><strong>PostHog:</strong> For more information about PostHog, please visit their Privacy Policy: <a href="https://posthog.com/privacy" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">https://posthog.com/privacy</a></li>
              </ul>

              <h3 className="text-xl font-semibold mb-2 mt-4">CI/CD tools</h3>
              <p className="text-foreground mb-4">
                <strong>GitHub:</strong> GitHub is provided by GitHub, Inc. GitHub is a development platform to host and review code, manage projects, and build software. For more information on what data GitHub collects and how the protection of the data is ensured, please visit GitHub Privacy Policy page: <a href="https://help.github.com/en/articles/github-privacy-statement" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">https://help.github.com/en/articles/github-privacy-statement</a>.
              </p>

              <h3 className="text-xl font-semibold mb-2 mt-4">Payments</h3>
              <p className="text-foreground mb-4">
                We provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).
              </p>
              <p className="text-foreground mb-4">The payment processors we work with are:</p>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li><strong>Stripe:</strong> Their Privacy Policy can be viewed at: <a href="https://stripe.com/us/privacy" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">https://stripe.com/us/privacy</a></li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Links to Other Sites</h2>
              <p className="text-foreground">
                Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
              </p>
              <p className="text-foreground">
                We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Children's Privacy</h2>
              <p className="text-foreground mb-4">
                Our Services are not intended for use by children under the age of 13 ("Children").
              </p>
              <p className="text-foreground mb-4">
                We do not knowingly collect personally identifiable information from Children under 13. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Changes to This Privacy Policy</h2>
              <p className="text-foreground mb-4">
                We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
              </p>
              <p className="text-foreground mb-4">
                We will let you know via email and/or a prominent notice on our Service, about any changes.
              </p>
              <p className="text-foreground">
                You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
              <p className="text-foreground">
                If you have any questions about this Privacy Policy, please contact us at support@voiceable.ai.
              </p>
            </section>
            </div>
          </div>
        </div>

        <Footer />
      </div>
    </>
  );
}

