#!/usr/bin/env node
/**
 * Writes public/sitemap.xml from static routes plus optional blog URLs from the API.
 * Blog URLs are included when SITEMAP_BLOG_API_URL or VITE_API_BASE_URL is set (GET …/blog_posts).
 * Otherwise only the static /blog route is listed (no individual post URLs).
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL ||
  process.env.VITE_SITE_URL ||
  "https://www.voiceable.dev"
).replace(/\/+$/, "");
const manifestPath = path.join(root, "src", "generated", "blogPosts.json");
const outFile = path.join(root, "public", "sitemap.xml");

const STATIC_ROUTES = [
  { loc: "/", changefreq: "weekly", priority: "1.0" },
  { loc: "/retail-ecommerce", changefreq: "monthly", priority: "0.8" },
  { loc: "/recruitment", changefreq: "monthly", priority: "0.8" },
  { loc: "/small-business", changefreq: "monthly", priority: "0.8" },
  { loc: "/blog", changefreq: "weekly", priority: "0.85" },
  { loc: "/pricing", changefreq: "monthly", priority: "0.9" },
  { loc: "/privacy", changefreq: "yearly", priority: "0.5" },
  { loc: "/terms", changefreq: "yearly", priority: "0.5" },
  { loc: "/sign-up", changefreq: "monthly", priority: "0.6" },
  { loc: "/login", changefreq: "monthly", priority: "0.6" },
  { loc: "/reset-password", changefreq: "monthly", priority: "0.4" },
  { loc: "/custom-agents", changefreq: "monthly", priority: "0.75" },
];

function normalizeApiBase(url) {
  const trimmed = String(url).trim().replace(/\/+$/, "");
  if (trimmed.startsWith("/")) {
    return /\/voiceable-api$/i.test(trimmed)
      ? trimmed
      : `${trimmed.replace(/\/+$/, "")}/voiceable-api`;
  }
  let normalized = trimmed
    .replace(/\/api\/v1$/i, "/voiceable-api")
    .replace(/\/voiceable_api$/i, "/voiceable-api");
  if (!/\/voiceable-api$/i.test(normalized)) {
    normalized = `${normalized}/voiceable-api`;
  }
  return normalized;
}

function isoDate(d) {
  if (!d) return new Date().toISOString().slice(0, 10);
  const t = Date.parse(d);
  if (Number.isNaN(t)) return new Date().toISOString().slice(0, 10);
  return new Date(t).toISOString().slice(0, 10);
}

function urlEntry(locPath, lastmod, changefreq, priority) {
  const loc = `${SITE_URL}${locPath.startsWith("/") ? locPath : `/${locPath}`}`;
  return `  <url>
    <loc>${loc}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
}

async function loadPostsFromApi() {
  const raw =
    process.env.SITEMAP_BLOG_API_URL ||
    process.env.NEXT_PUBLIC_API_BASE_URL ||
    process.env.VITE_API_BASE_URL;
  if (!raw) return [];

  const base = normalizeApiBase(raw).replace(/\/+$/, "");
  const url = `${base}/blog_posts`;

  try {
    const res = await fetch(url, {
      headers: { Accept: "application/json" },
    });
    if (!res.ok) {
      console.warn(`Sitemap: blog API ${res.status} from ${url}; skipping post URLs.`);
      return [];
    }
    const json = await res.json();
    const data = json?.data;
    if (!Array.isArray(data)) return [];
    return data.map((p) => ({
      slug: p.slug,
      updatedAt: p.updated_at,
      publishedAt: p.published_at,
    }));
  } catch (e) {
    console.warn("Sitemap: blog API fetch failed;", e.message || e);
    return [];
  }
}

function loadPostsFromManifest() {
  if (!fs.existsSync(manifestPath)) return [];
  try {
    const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
    return manifest.posts || [];
  } catch {
    return [];
  }
}

async function main() {
  let posts = await loadPostsFromApi();
  const source = posts.length > 0 ? "API" : "manifest";

  if (posts.length === 0) {
    posts = loadPostsFromManifest();
  }

  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    "  <!-- Auto-generated by scripts/generate-sitemap.mjs -->",
  ];

  const today = new Date().toISOString().slice(0, 10);

  for (const r of STATIC_ROUTES) {
    lines.push(urlEntry(r.loc, today, r.changefreq, r.priority));
  }

  for (const post of posts) {
    if (!post?.slug) continue;
    const lastmod = isoDate(post.updatedAt || post.updated_at || post.publishedAt || post.published_at);
    lines.push(urlEntry(`/blog/${post.slug}`, lastmod, "monthly", "0.7"));
  }

  lines.push("</urlset>", "");
  fs.writeFileSync(outFile, lines.join("\n"));
  console.log(
    `Sitemap: ${STATIC_ROUTES.length} static + ${posts.length} posts (${source}) → ${path.relative(root, outFile)}`
  );
}

await main();
